sudo: required
services: 
  - docker

before_install:
  - docker build -t reservoirdog/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true reservoirdog/docker-react npm run test

language: generic
